//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceControl.EasyJoinServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EasyJoinServiceReference.EasyJoinServiceSoap")]
    public interface EasyJoinServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 commNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertEquipmentData", ReplyAction="*")]
        EasyJoinServiceReference.InsertEquipmentDataResponse InsertEquipmentData(EasyJoinServiceReference.InsertEquipmentDataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 commNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEquipmentData", ReplyAction="*")]
        EasyJoinServiceReference.DeleteEquipmentDataResponse DeleteEquipmentData(EasyJoinServiceReference.DeleteEquipmentDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEquipmentDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEquipmentData", Namespace="http://tempuri.org/", Order=0)]
        public EasyJoinServiceReference.InsertEquipmentDataRequestBody Body;
        
        public InsertEquipmentDataRequest() {
        }
        
        public InsertEquipmentDataRequest(EasyJoinServiceReference.InsertEquipmentDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertEquipmentDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string commNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string receiveString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string level;
        
        public InsertEquipmentDataRequestBody() {
        }
        
        public InsertEquipmentDataRequestBody(string commNo, string receiveString, string level) {
            this.commNo = commNo;
            this.receiveString = receiveString;
            this.level = level;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEquipmentDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEquipmentDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public EasyJoinServiceReference.InsertEquipmentDataResponseBody Body;
        
        public InsertEquipmentDataResponse() {
        }
        
        public InsertEquipmentDataResponse(EasyJoinServiceReference.InsertEquipmentDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertEquipmentDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertEquipmentDataResult;
        
        public InsertEquipmentDataResponseBody() {
        }
        
        public InsertEquipmentDataResponseBody(string InsertEquipmentDataResult) {
            this.InsertEquipmentDataResult = InsertEquipmentDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEquipmentDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEquipmentData", Namespace="http://tempuri.org/", Order=0)]
        public EasyJoinServiceReference.DeleteEquipmentDataRequestBody Body;
        
        public DeleteEquipmentDataRequest() {
        }
        
        public DeleteEquipmentDataRequest(EasyJoinServiceReference.DeleteEquipmentDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteEquipmentDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string commNo;
        
        public DeleteEquipmentDataRequestBody() {
        }
        
        public DeleteEquipmentDataRequestBody(string commNo) {
            this.commNo = commNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEquipmentDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEquipmentDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public EasyJoinServiceReference.DeleteEquipmentDataResponseBody Body;
        
        public DeleteEquipmentDataResponse() {
        }
        
        public DeleteEquipmentDataResponse(EasyJoinServiceReference.DeleteEquipmentDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteEquipmentDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteEquipmentDataResult;
        
        public DeleteEquipmentDataResponseBody() {
        }
        
        public DeleteEquipmentDataResponseBody(string DeleteEquipmentDataResult) {
            this.DeleteEquipmentDataResult = DeleteEquipmentDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EasyJoinServiceSoapChannel : EasyJoinServiceReference.EasyJoinServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EasyJoinServiceSoapClient : System.ServiceModel.ClientBase<EasyJoinServiceReference.EasyJoinServiceSoap>, EasyJoinServiceReference.EasyJoinServiceSoap {
        
        public EasyJoinServiceSoapClient() {
        }
        
        public EasyJoinServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EasyJoinServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EasyJoinServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EasyJoinServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EasyJoinServiceReference.InsertEquipmentDataResponse EasyJoinServiceReference.EasyJoinServiceSoap.InsertEquipmentData(EasyJoinServiceReference.InsertEquipmentDataRequest request) {
            return base.Channel.InsertEquipmentData(request);
        }
        
        public string InsertEquipmentData(string commNo, string receiveString, string level) {
            EasyJoinServiceReference.InsertEquipmentDataRequest inValue = new EasyJoinServiceReference.InsertEquipmentDataRequest();
            inValue.Body = new EasyJoinServiceReference.InsertEquipmentDataRequestBody();
            inValue.Body.commNo = commNo;
            inValue.Body.receiveString = receiveString;
            inValue.Body.level = level;
            EasyJoinServiceReference.InsertEquipmentDataResponse retVal = ((EasyJoinServiceReference.EasyJoinServiceSoap)(this)).InsertEquipmentData(inValue);
            return retVal.Body.InsertEquipmentDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EasyJoinServiceReference.DeleteEquipmentDataResponse EasyJoinServiceReference.EasyJoinServiceSoap.DeleteEquipmentData(EasyJoinServiceReference.DeleteEquipmentDataRequest request) {
            return base.Channel.DeleteEquipmentData(request);
        }
        
        public string DeleteEquipmentData(string commNo) {
            EasyJoinServiceReference.DeleteEquipmentDataRequest inValue = new EasyJoinServiceReference.DeleteEquipmentDataRequest();
            inValue.Body = new EasyJoinServiceReference.DeleteEquipmentDataRequestBody();
            inValue.Body.commNo = commNo;
            EasyJoinServiceReference.DeleteEquipmentDataResponse retVal = ((EasyJoinServiceReference.EasyJoinServiceSoap)(this)).DeleteEquipmentData(inValue);
            return retVal.Body.DeleteEquipmentDataResult;
        }
    }
}
